---
- name: Load configuration
  ansible.builtin.include_tasks: 01_load_config.yml

- name: "Configure Sterling External Authentication Server Namespace"
  ansible.builtin.include_tasks: 02_configure_namespace.yml

- name: "Deploy the SEAS helm chart configuration"
  ansible.builtin.include_tasks: 03_deploy_seas.yml
