---
- name: Collect DB2 Pod Information
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ db2_namespace }}"
    label_selectors:
      - app={{ db2_crd_name }}
      - role=db
  register: db2_pod

- name: Register DB2 pod name
  ansible.builtin.set_fact:
    db2_pod_name: "{{ db2_pod.resources[0].metadata.name }}"

- name: Register DB2 values to update with
  ansible.builtin.set_fact:
    db_values:
      STMT_CONC: "LITERALS"
      SELF_TUNING_MEM: "ON"
      LOCKLIST: "AUTOMATIC"
      MAXLOCKS: "AUTOMATIC"
      PCKCACHESZ: "AUTOMATIC"
      SHEAPTHRES_SHR: "AUTOMATIC"
      SORTHEAP: "AUTOMATIC"
      NUM_IOCLEANERS: "AUTOMATIC"
      NUM_IOSERVERS: "AUTOMATIC"
      DFT_PREFETCH_SZ: "AUTOMATIC"
      MAXAPPLS: "AUTOMATIC"
      APPLHEAPSZ: "AUTOMATIC"
      APPL_MEMORY: "AUTOMATIC"
      DBHEAP: "AUTOMATIC"
      LOGFILSIZ: "65536"
      LOGPRIMARY: "40"
      LOGSECOND: "12"
      NUM_LOG_SPAN: "40"
      DFT_DEGREE: "1"
      LOGBUFSZ: "2152"
      STMTHEAP: "51200 AUTOMATIC"
      CATALOGCACHE_SZ: "300"
      UTIL_HEAP_SZ: "AUTOMATIC"
      CHNGPGS_THRESH: "80"

- name: Update the DB2 CR associated with B2BI
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: db2u.databases.ibm.com/v1
      kind: Db2uCluster
      metadata:
        name: "{{ db2_crd_name }}"
        namespace: "{{ db2_namespace }}"
      spec:
        environment:
          database:
            settings:
              "{{ db_values }}"

- name: Wait for the DB2 deployment to finish before moving on
  kubernetes.core.k8s_info:
    kind: Db2uCluster
    namespace: "{{ db2_namespace }}"
    name: "{{ db2_crd_name }}"
  register: result
  until: result.resources[0].status.state == "Ready"
  retries: 40
  delay: 30

- name: Wait 180 seconds for database configmap to Update
  ansible.builtin.pause:
    seconds: 180
