---
- name: Look Up DB2 Information
  when: deploy_db2
  block:
    - name: Collect DB2 networking information
      kubernetes.core.k8s_info:
        kind: Service
        namespace: "{{ db2_namespace }}"
        name: "c-{{ db2_crd_name }}-db2u"
      register: db2_service_output

    - name: Register Database Networking Configuration
      ansible.builtin.set_fact:
        b2bi_dbvender: "DB2"
        b2bi_dbhost: "c-{{ db2_crd_name }}-db2u.{{ db2_namespace }}.svc.cluster.local"
        b2bi_dbport: >-
          {{ db2_service_output.resources[0].spec.ports
          | selectattr('name', '==', 'db2-server')
          | map(attribute='port') | first }}
