---
- name: Load SSP CM Config
  ansible.builtin.include_tasks: 01_load_config.yml

- name: "Configure Sterling Secure Proxy Configuration Manager Namespace"
  ansible.builtin.include_tasks: 02_configure_namespace.yml

- name: "Deploy the SSP CM helm chart configuration"
  ansible.builtin.include_tasks: 03_deploy_ssp_cm.yml
