---
seas_release_name: auto-seas
seas_version: 6.1.0.2.03
seas_license_type: non-prod

seas_namespace: seas

seas_registry_secret: ibm-entitlement-key
seas_registry: cp.icr.io
seas_registry_user: cp
seas_registry_key:
seas_serviceaccount: seas-sa
seas_pvc: seas-pvc

seas_secret: ibm-seas-secret
seas_sys_passphrase: Passw0rd@123
seas_admin_password: Passw0rd@123
seas_keystore_passphrase: Change1t@
seas_truststore_passphrase: Change1t@

versions:
  6.1.0.2.03:
    helm_chart_version: 1.5.4
