---
- name: Collect DB2 Pod Information
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ db2_namespace }}"
    label_selectors:
      - app={{ db2_crd_name }}
      - role=db
  register: db2_pod

- name: Register DB2 pod name
  ansible.builtin.set_fact:
    db2_pod_name: "{{ db2_pod.resources[0].metadata.name }}"

- name: Update the DB2 CR associated with ITXA
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: db2u.databases.ibm.com/v1
      kind: Db2uInstance
      metadata:
        name: "{{ db2_crd_name }}"
        namespace: "{{ db2_namespace }}"
      spec:
        environment:
          databases:
            - name: "{{ db2_dbname }}"
              dbConfig:
                "{{ db_values }}"
              storage:
                - name: data
                  type: template
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: "{{ db2_storage_size }}"
                    storageClassName: "{{ block_storage_class }}"
                - name: activelogs
                  type: template
                  spec:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 10Gi
                    storageClassName: "{{ block_storage_class }}"

- name: Wait for the DB2 deployment to finish before moving on
  kubernetes.core.k8s_info:
    kind: Db2uInstance
    namespace: "{{ db2_namespace }}"
    name: "{{ db2_crd_name }}"
  register: result
  until: result.resources[0].status.state == "Ready"
  retries: 40
  delay: 30

- name: Wait 180 seconds for database configmap to Update
  ansible.builtin.pause:
    seconds: 180
