---
- name: Load configuration
  ansible.builtin.include_tasks: 01_load_config.yml

- name: Deploy DB2
  ansible.builtin.include_role:
    name: db2_deploy
  when: deploy_db2

- name: "Configure Itxa namespace"
  ansible.builtin.include_tasks: 02_configure_namespace.yml

- name: Configure DB2 for Itxa
  ansible.builtin.include_tasks: 03_configure_db2_for_itxa.yml
  when: deploy_db2

- name: "Define database configuration for Itxa"
  ansible.builtin.include_tasks: 04_define_database.yml

- name: "Deploy Itxa helm chart and configuration"
  ansible.builtin.include_tasks: 05_deploy_itxa.yml
