---
deploy_ibm_catalog_source: false
deploy_b2bi: false
deploy_ssp_cm: false
deploy_ssp_engine: false
deploy_connect_direct: false
deploy_connect_direct_web_services: false
deploy_seas: true

registry: cp.icr.io
registry_user: cp

file_storage_class: ocs-external-storagecluster-cephfs
block_storage_class: ocs-external-storagecluster-ceph-rbd
