---
- name: Load Config for SSP PS
  ansible.builtin.include_tasks: 01_load_config.yml

- name: "Configure Sterling Secure Proxy Ps Namespace"
  ansible.builtin.include_tasks: 02_configure_namespace.yml

- name: "Deploy the SSP PS helm chart configuration"
  ansible.builtin.include_tasks: 03_deploy_ssp_ps.yml
