---
- name: Create registry secret content "{{ db2_registry_secret }}"
  no_log: true
  vars:
    auth: "{{ registry_user }}:{{ entitlement_key }}"
    auth_b64: "{{ auth | b64encode }}"
    content:
      - '{"auths":{"{{ registry }}":{"username":"{{ registry_user }}","password":"{{ entitlement_key }}",'
      - '"email":"{{ registry_user }}","auth":"{{ auth_b64 }}"}'
      - "}"
      - "}"
  ansible.builtin.set_fact:
    new_secret: "{{ content | join('') }}"

- name: Template DB2 registry secret for reuse
  ansible.builtin.template:
    src: templates/db2-registry-secret.yml.j2
    dest: ../output/{{ db2_namespace }}/{{ db2_namespace }}-db2-registry-secret.yml
    mode: '0644'

- name: Generate db2 registry secret "{{ db2_registry_secret }}"
  no_log: true
  kubernetes.core.k8s:
    state: present
    src: ../output/{{ db2_namespace }}/{{ db2_namespace }}-db2-registry-secret.yml

- name: Template the db2 secret for reuse
  ansible.builtin.template:
    src: templates/db2-secret.yml.j2
    dest: ../output/{{ db2_namespace }}/{{ db2_namespace }}-{{ db2_secret }}.yml
    mode: '0644'

- name: Generate db2 secret "{{ db2_secret }}"
  kubernetes.core.k8s:
    state: present
    src: ../output/{{ db2_namespace }}/{{ db2_namespace }}-{{ db2_secret }}.yml
