- name: Template the Db2uCluster for reuse
  ansible.builtin.template:
    src: templates/db2ucluster.yml.j2
    dest: ../output/{{ db2_namespace }}/{{ db2_namespace }}-{{ db2_crd_name }}-cr-instance.yml
    mode: '0644'

- name: Deploy DB2
  kubernetes.core.k8s:
    state: present
    src: ../output/{{ db2_namespace }}/{{ db2_namespace }}-{{ db2_crd_name }}-cr-instance.yml

- name: Wait for Db2uCluster to start
  ansible.builtin.pause:
    seconds: 30

- name: Wait for the DB2 deployment to finish before moving on
  kubernetes.core.k8s_info:
    api_version: db2u.databases.ibm.com/v1
    kind: Db2uCluster
    namespace: "{{ db2_namespace }}"
    name: "{{ db2_crd_name }}"
  register: result
  until: result.resources[0].status.state == "Ready"
  retries: 40
  delay: 30
