site_name: Sterling Data Exchange Automation
site_description: Documentation for the Sterling Data Exchange Automation project
site_author: Knick Kennedy
site_url: https://knickkennedy.github.io/sterling-data-exchange-automation/

repo_url: https://github.com/Knickkennedy/sterling-data-exchange-automation
repo_name: GitHub
edit_uri: edit/main/docs/
docs_dir: src

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en

nav:
  - Home: index.md
  - Getting Started:
      - Overview: 01-getting-started/overview.md
      - Installation: 01-getting-started/installation.md
  - Usage:
      - Running the Application: 02-usage/running.md
      - Configuration:
          - Introduction: 02-usage/index.md
          - Global: 02-usage/configuration/global.md
          - B2Bi: 02-usage/configuration/b2bi.md
  - Development:
      - Contributing: 05-development/contributing.md
  - License: license.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages:
      filename: .pages
      collapse_single_pages: false
      strict: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Knickkennedy/sterling-data-exchange-automation
