---
- name: Load ITXA configuration
  ansible.builtin.include_tasks: 01_load_config.yml

- name: Configure Sterling CD Namespace
  ansible.builtin.include_tasks: 02_configure_namespace.yml

- name: Deploy Sterling CD Helm Chart
  ansible.builtin.include_tasks: 03_deploy_cd.yml
