name: build-deployer-doc

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create and install venv dependencies
        run: |
          python3 -m venv ~/.venv/sde-deployer-doc
          . ~/.venv/sde-deployer-doc/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r docs/requirements.txt
          pip install sphinx_rtd_theme

      - name: Build MkDocs site
        run: |
          ~/.venv/sde-deployer-doc/bin/mkdocs build
        working-directory: docs

      - name: Add .nojekyll to prevent Jekyll processing
        run: touch site/.nojekyll
        working-directory: docs

      - name: Deploy site to GitHub Pages
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          ~/.venv/sde-deployer-doc/bin/mkdocs gh-deploy --force
        working-directory: docs
